# /icp_registration:
#   ros__parameters:
#     use_sim_time: false 
#     rough_leaf_size: 0.4
#     refine_leaf_size: 0.1
#     pcd_path: ""
#     map_frame_id: "map"
#     odom_frame_id: "odom"
#     range_odom_frame_id: "lidar_odom"
#     laser_frame_id: "livox_frame"
#     pointcloud_topic: "/livox/lidar/pointcloud"
#     thresh: 0.1
#     xy_offset: 0.2
#     yaw_offset: 30.0
#     yaw_resolution: 10.0
#     initial_pose: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] # x,y,z,roll,pitch,yaw
/small_gicp_relocalization:
  ros__parameters:
    num_threads: 4
    num_neighbors: 10
    global_leaf_size: 0.25
    registered_leaf_size: 0.25
    max_dist_sq: 1.0
    map_frame_id: "map"
    odom_frame_id: "odom"
    vel_ref_frame: "base_link"
    lidar_frame: "livox_frame"
    # The prior_pcd_file does not need to be specified since it going to be set by defaults in launch.
    # prior_pcd_file: ""